version: '3'
services:
    database:
        image: mysql
        container_name: mysql_db
        ports:
            - 3308:3306
        environment: 
            MYSQL_ROOT_PASSWORD: 'root123'
            MYSQL_DATABASE: 'empresa'
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
        networks:
            network:
                aliases:
                    - database
    node-app:
        build: 
            context: ./app
            dockerfile: dockerfile
        container_name: index_js
        entrypoint: npm run dev
        ports:
            - 5000:3300
        volumes: 
            - ./app:/app
        networks: 
            network:
                aliases: 
                    - node-app
networks:
    network:
        name: network