version: '3'
services:
    database-2:
        image: mysql
        container_name: mysql_db
        ports:
            - 3309:3307
        environment: 
            MYSQL_ROOT_PASSWORD: 'toor123'
            MYSQL_DATABASE: 'db_envio'
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
        networks:
            network:
                aliases:
                    - database-2
    node-app-2:
        build: 
            context: ./app
            dockerfile: dockerfile
        container_name: index_js
        entrypoint: npm run dev
        ports:
            - 5001:3400
        volumes: 
            - ./app:/app
        networks: 
            network:
                aliases: 
                    - node-app-2
networks:
    network:
        name: network-2